config/routes.rb
Rails.application.routes.draw do
  namespace :users_office do
    get 'graphics/index'
  end
  namespace :users_office do
    get 'profile/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  namespace :users_office do
    get 'welcome/index'

    get 'meals/index'
    resources :meals

    get 'diets/index'
    resources :diets

    get 'users/index'
    resources :users

  end

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #get 'dados', to: 'users_office/users#edit'

  root to: 'users_office/welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :user
  belongs_to :meal
  has_rich_text :description
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :diets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :picture
  has_many :diets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_office/diets_controller.rb
class UsersOffice::DietsController < UsersOfficeController
  before_action :authenticate_user!
  before_action :set_diet, only:[:show,:update,:edit,:destroy]
  before_action :set_select_user, only:[:new,:edit]
  before_action :set_select_meal, only:[:new,:edit]
  
  def index 
   #@diets = Diet.all
   @diets = Diet.where(params[:user_id]).page(params[:page]).per(6)
  end

  def show
  end

  def new
   @diet = Diet.new
  end

  def create
   @select_user == current_user.name
    
   @diet = Diet.new(params_diet)
   if @diet.save
   redirect_to users_office_diets_index_path, notice: 'Dieta ... criada com sucesso !'
   else
   render :new
   end
  end

  def update
   if @diet.update(params_diet)
    redirect_to users_office_diets_index_path, notice: 'Dieta... atualizada com sucesso !'
   else
    render :edit
   end 
  end 

  def destroy
   if @diet.destroy
    redirect_to users_office_diets_index_path, notice: 'Dieta ... excluida com sucesso !'
   else
    render :index
   end
  end
  
  private

  def set_user
    @user = User.find(current_user.id)
   end

  def set_diet
   @diet = Diet.find(params[:id])
  end

  def set_select_user
   @select_user = User.where(params[:user_id])
  end

  def set_select_meal
    @select_meal = Meal.all.pluck(:description,:id)
   end

  def params_diet
   params.require(:diet).permit(:date_initial,:date_final,:weight,:height,:ideal_weight,:schedule,:description,:user_id,:meal_id)
  end
end

app/controllers/users_office/graphics_controller.rb
class UsersOffice::GraphicsController < UsersOfficeController
  before_action :authenticate_user!
  def index
    @diets = Diet.group(:weight).count(:meal_id)
  end
end

app/controllers/users_office/meals_controller.rb
class UsersOffice::MealsController < UsersOfficeController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users_office/profile_controller.rb
class UsersOffice::ProfileController < UsersOfficeController
  before_action :authenticate_user!
  before_action :set_user

  def index
  end

  def edit
  end

  def update
    if @user.update(params_user)
      redirect_to users_office_diets_index_path, notice: 'Usuário atualizado com sucesso !'
     else
      render :edit
     end
  end

  private

  def set_user
   @user = User.find(current_user.id)
  end

  def params_user
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:picture)
   end

end

app/controllers/users_office/users_controller.rb
class UsersOffice::UsersController < UsersOfficeController
  before_action :authenticate_user!
  before_action :set_user, only:[:show,:edit,:update,:destroy]
  
  def index
    @users = User.all
  end

  def show
  end

  def new
   @user = User.new
  end

  def create
   @user = User.new(params_user)
   if @user.save
    redirect_to users_office_users_index_path, notice: 'Usuário criado com sucesso !'
   else
    render :new
   end
  end

  def update
   if @user.update(params_user)
    redirect_to users_office_users_index_path, notice: 'Usuário atualizado com sucesso !'
   else
    render :edit
   end
  end

  def destroy
   if @user.destroy
    redirect_to users_office_users_index_path, notice: 'Usuário excluido com sucesso !'
   else
    render :index
   end
  end

  private

  def set_user
   @user = User.find(params[:id])
  end

  def params_user
   params.require(:user).permit(:name,:email,:password,:password_confirmation,:picture)
  end
end

app/controllers/users_office/welcome_controller.rb
class UsersOffice::WelcomeController < UsersOfficeNewController
  def index
  end
end

app/controllers/users_office_controller.rb
class UsersOfficeController < ApplicationController
  layout 'users'
end

app/controllers/users_office_new_controller.rb
class UsersOfficeNewController < ApplicationController
  layout 'users_new'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_office/diets_helper.rb
module UsersOffice::DietsHelper
end

app/helpers/users_office/graphics_helper.rb
module UsersOffice::GraphicsHelper
end

app/helpers/users_office/meals_helper.rb
module UsersOffice::MealsHelper
end

app/helpers/users_office/profile_helper.rb
module UsersOffice::ProfileHelper
end

app/helpers/users_office/users_helper.rb
module UsersOffice::UsersHelper
end

app/helpers/users_office/welcome_helper.rb
module UsersOffice::WelcomeHelper
end

app/helpers/users_office_helper.rb
module UsersOfficeHelper
end

app/helpers/users_office_new_helper.rb
module UsersOfficeNewHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users_office/diets/edit.html.erb
<%= render partial: 'users_office/diets/shared/form' , locals: { action_message: 'Editando Dieta'}%>

app/views/users_office/diets/index.html.erb
<h1>Listagem de Dietas </h1>

<hr>
<%= link_to 'Novo', new_users_office_diet_path , class: 'btn btn-success'%> | <%= notice %>  | 
<hr>

<table class='table-hover'>
  <thead> 
     <tr>
      <th> # </th>
      <th> Nome </th>
      <th> Refeição </th>
      <th> Data Inicial </th>
      <th> Data Fim </th>
      <th> Peso </th>
      <th> Altura </th>
      <th> Peso Ideal</th>
      <th> Schedule </th>
      <th> Description </th>
      <th> Açoes </th>
     </tr>
  </thead>
  <% @diets.where(:user_id => current_user.id).each.with_index do |diet,index|%>
  <tbody> 
     <tr>
      <th> <%= diet.id %></th>
      <th> <%= diet.user.name %> </th>
      <th> <%= diet.meal.description %>  </th>
      <th> <%= diet.date_initial.to_date.strftime("%d/%m/%Y")  %> </th>
      <th> <%= diet.date_final.to_date.strftime("%d/%m/%Y")  %>  </th>
      <th> <%= diet.weight %>  </th>
      <th> <%= diet.height %>  </th>
      <th> <%= diet.ideal_weight %> </th>
      <th> <%= diet.schedule.to_time.strftime("%I:%M%p") %>  </th>
      <th> <%= diet.description %>  </th>
      <th>
        <%= link_to 'Voltar', users_office_welcome_index_path %> |  
        <%= link_to 'Mostrar', users_office_diet_path(diet) %> | 
        <%= link_to 'Editar',  edit_users_office_diet_path(diet)%> | 
        <%= link_to 'Deletar', users_office_diet_path(diet), method: :delete, data:{ confirm: 'Tem Certeza'}%> | 
      </th>
     </tr>
  </tbody> 
     
  <% end %>
   
 

</table>

<hr>
 <div class="text-center"> <%= paginate @diets %> </div>

app/views/users_office/diets/new.html.erb
<%= render partial: 'users_office/diets/shared/form', locals: { action_message: 'Nova Dieta'}%>

app/views/users_office/diets/show.html.erb
<hr>
 <h1>Mostrando Dieta</h1>
<hr>

<table>
  <thead> 
     <tr>
      <th> # </th>
      <th> Nome </th>
      <th> Refeição </th>
      <th> Data Inicial </th>
      <th> Data Fim </th>
      <th> Peso </th>
      <th> Altura </th>
      <th> Peso Ideal</th>
      <th> Schedule </th>
      <th> Description </th>
      <th> Açoes </th>
     </tr>
  </thead>
  
  <tbody> 
     <tr>
      <th> <%= @diet.id %> </th>
      <th> <%= @diet.user.name %>  </th>
      <th> <%= @diet.meal.description %>  </th>
      <th> <%= @diet.date_initial.to_date.strftime("%d/%m/%Y") %> </th>
      <th> <%= @diet.date_final.to_date.strftime("%d/%m/%Y") %>  </th>
      <th> <%= @diet.weight %>  </th>
      <th> <%= @diet.height %>  </th>
      <th> <%= @diet.ideal_weight %> </th>
      <th> <%= @diet.schedule %>  </th>
      <th> <%= @diet.description %>  </th>
      <th> 
        <%= link_to 'Voltar',  users_office_diets_path %> | 
        <%= link_to 'Editar',  edit_users_office_diet_path(@diet)%> | 
        <%= link_to 'Deletar', users_office_diet_path(@diet), method: :delete, data:{ confirm: 'Tem Certeza'}%> | 
      </th>
     </tr>
  </tbody>
  
</table>

app/views/users_office/graphics/index.html.erb
<p> <%= link_to 'Voltar', users_office_diets_index_path %> </p>

<%= bar_chart @diets %>

app/views/users_office/meals/index.html.erb
<h1>UsersOffice::Meals#index</h1>
<p>Find me in app/views/users_office/meals/index.html.erb</p>

app/views/users_office/profile/edit.html.erb
<%= render partial: 'users_office/profile/shared/form', locals: { action_message: 'Editando Usuário'}%>

app/views/users_office/profile/shared/_form.html.erb
<% if @user.errors.any? %>
   <% @user.errors.full_messages.each do |message| %>
        <%= message %> 
  <% end %>
<% end %>

<hr>
<h3> <%= action_message %></h3> 
<hr>
              
<%= form_with(url: users_office_profile_path, model: @user ,local: true) do |form| %>
  <div class="form-row">
    <div class="form-group col-md-6">
       <%= form.label :name %>
       <%= form.text_field :name, placeholder:"Email do usuário", class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :email %>
      <%= form.text_field :email, placeholder:"Email do usuário", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, placeholder:"Senha", class: 'form-control' %>
  </div>
  <div class="form-group">
     <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation , placeholder:"Confirmação da senha", class: 'form-control'  %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :picture %><br>
      <%= form.file_field :picture , class: 'form-control'%>
    </div>
  </div>
  
  <%= form.submit "Salvar", class: 'btn btn-primary' %>
<% end %>                                                       

app/views/users_office/users/edit.html.erb
<%= render partial: 'users_office/users/shared/form' , locals: { action_message: 'Editando Usuários'}%>

app/views/users_office/users/index.html.erb
<h1>Listagem de Usuários</h1>

<hr>
 <%= notice %>  | <%= link_to 'Novo', new_users_office_user_path %>
<hr>

<table class="table table-hover">
  <thead> 
     <tr>
      <th> # </th>
      <th> Nome </th>
      <th> Email </th>
      <th> Criado em : </th>
      <th> Atualizado em : </th>
      <th> Açoes </th>
     </tr>
  </thead>
  <% @users.each do |user|%>
  <tbody> 
     <tr>
      <th> <%= user.id %> </th>
      <th> <%= user.name %>  </th>
      <th> <%= user.email %>  </th>
      <th> <%= user.created_at %> </th>
      <th> <%= user.updated_at %>  </th>
      <th> 
        <%= link_to 'Voltar', users_office_welcome_index_path %> | 
        <%= link_to 'Mostrar', users_office_user_path(user)%> | 
        <%= link_to 'Editar',  edit_users_office_user_path(user)%> | 
        <%= link_to 'Deletar', users_office_user_path(user), method: :delete, data:{ confirm: 'Tem Certeza'}%> | 
      </th>
     </tr>
  </tbody>
  <% end %>
</table>

app/views/users_office/users/new.html.erb
<%= render partial: 'users_office/users/shared/form', locals: { action_message: 'Novo Usuário'}%>

app/views/users_office/users/shared/_form.html.erb
<% if @user.errors.any? %>
   <% @user.errors.full_messages.each do |message| %>
        <%= message %> 
  <% end %>
<% end %>

<hr>
<h3> <%= action_message %></h3> 
<hr>
   
 <%= form_with(model:[:users_office,@user],local: true) do |form| %>
  <div class="form-row">
    <div class="form-group col-md-6">
       <%= form.label :name %>
       <%= form.text_field :name, placeholder:"Email do usuário", class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :email %>
      <%= form.text_field :email, placeholder:"Email do usuário", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, placeholder:"Senha", class: 'form-control' %>
  </div>
  <div class="form-group">
     <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation , placeholder:"Confirmação da senha", class: 'form-control'  %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :picture %><br>
      <%= form.file_field :picture , class: 'form-control'%>
    </div>
  </div>
  
  <%= form.submit "Salvar", class: 'btn btn-primary' %>
<% end %>                          

app/views/users_office/users/show.html.erb
<hr>
<h1>Mostrando Usuário</h1>
<hr>

<table>
  <thead> 
     <tr>
      <th> # </th>
      <th> Foto </th>
      <th> Nome </th>
      <th> Email </th>
      <th> Criado em : </th>
      <th> Atualizado em : </th>
      <th> Açoes </th>
     </tr>
  </thead>
  
  <tbody> 
     <tr>
      <th> <%= @user.id %> </th>
      <th><%= image_tag(@user.picture, size: '100x100') if @user.picture.attached? %></th>
      <th> <%= @user.name %>  </th>
      <th> <%= @user.email %>  </th>
      <th> <%= @user.created_at %> </th>
      <th> <%= @user.updated_at %>  </th>
      <th> 
        <%= link_to 'Voltar', users_office_users_path%> | 
        <%= link_to 'Editar',  edit_users_office_user_path(@user)%> | 
        <%= link_to 'Deletar', users_office_user_path(@user), method: :delete, data:{ confirm: 'Tem Certeza'}%> | 
      </th>
     </tr>
  </tbody>
  
</table>

app/views/users_office/welcome/index.html.erb
<p> 
<%= link_to 'Efetuar Login', users_office_diets_path , class: 'btn btn-primary'%>
</p>